// Generated by Wrangler on Thu Feb 06 2025 16:49:41 GMT-0300 (Brasilia Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BASE_URL: string;
	BETTER_AUTH_SECRET: string;
	DATABASE_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_SECRET: string;
	STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_KEY: string;
}
